docs: Name change
vertigis/vertigis-workflow-sdk pull request #14
Opened 2022-01-20 01:20 UTC by connerleverett

Convert Geocortex -> VertiGIS Studio
Convert geocortex.com -> vertigisstudio.com

2022-01-20 01:20 UTC, connerleverett commented
To be merged after Feb 14th 2022

2022-01-27 20:47 UTC, kenlyon requested changes

2022-01-27 20:47 UTC, kenlyon commented on README.md
> +This SDK makes it easy to create custom activity packs for [VertiGIS Studio Workflow](https://www.vertigisstudio.com/products/geocortex-workflow/).
https://vertigisstudio.com/products/vertigis-studio-workflow/

2022-01-27 21:40 UTC, connerleverett commented on README.md
> +This SDK makes it easy to create custom activity packs for [VertiGIS Studio Workflow](https://www.vertigisstudio.com/products/geocortex-workflow/).
Updated.

2022-01-27 22:27 UTC, kenlyon approved these changes

2022-02-16 16:32 UTC, merged